services:
  web:
    build: .
    ports:
      - "31337:31337"
    environment:
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      - ML_API_KEY=$ML_API_KEY
